// 用户列表
export const USER_LIST = Object.freeze([
  {
    id: "1",
    name: "11",
    age: 14,
    phone: "18501742155",
    email: "123@qq.com",
    education: "本科",
    graduationschool: "a大学",
    profession: "前端开发",
    profile: "我不会下班",
  },
  {
    id: "2",
    name: "22",
    age: 15,
    phone: "18501742155",
    email: "123@qq.com",
    education: "本科",
    graduationschool: "a大学",
    profession: ".NET开发",
    profile: "我不会下班",
  },
  {
    id: "3",
    name: "33",
    age: 16,
    phone: "18501742155",
    email: "123@qq.com",
    education: "本科",
    graduationschool: "a大学",
    profession: "JAVA开发",
    profile: "我不会下班",
  },
  {
    id: "4",
    name: "44",
    age: 17,
    phone: "18501742155",
    email: "123@qq.com",
    education: "本科",
    graduationschool: "a大学",
    profession: "PHP开发",
    profile: "我不会下班",
  },
]);
